concrete StructuralHye of Structural = CatHye ** open Prelude, ResHye, ParadigmsHye in {
oper
  postPrep : Str -> Case -> Prep = \s,c -> lin Prep {s=s;c=c;isPre=False} ;
  simpleNP : Str -> Number -> Person -> NP = \s,n,p -> lin NP {s=\\_ => s;a={n=n;p=p}} ;
  casePron : (nom,dat,ablat,instr,loc,poss : Str) -> Number -> Person -> Pron =
    \nom,dat,ablat,instr,loc,poss,n,p -> lin Pron {
      s=table {Nom=>nom;Dat=>dat;Ablat=>ablat;Instr=>instr;Loc=>loc};
      empty=poss;a={n=n;p=p}
    } ;
lin i_Pron = casePron "ես" "ինձ" "ինձնից" "ինձնով" "ինձ մոտ" "իմ" Sg P1 ;
lin youSg_Pron = casePron "դու" "քեզ" "քեզնից" "քեզնով" "քեզ մոտ" "քո" Sg P2 ;
lin he_Pron, she_Pron, it_Pron = casePron "նա" "նրան" "նրանից" "նրանով" "նրա մոտ" "նրա" Sg P3 ;
lin we_Pron = casePron "մենք" "մեզ" "մեզնից" "մեզնով" "մեզ մոտ" "մեր" Pl P1 ;
lin youPl_Pron = casePron "դուք" "ձեզ" "ձեզնից" "ձեզնով" "ձեզ մոտ" "ձեր" Pl P2 ;
lin youPol_Pron = casePron "Դուք" "Ձեզ" "Ձեզնից" "Ձեզնով" "Ձեզ մոտ" "Ձեր" Pl P2 ;
lin they_Pron = casePron "նրանք" "նրանց" "նրանցից" "նրանցով" "նրանց մոտ" "նրանց" Pl P3 ;
lin and_Conj = mkConj "և" ;
lin or_Conj = mkConj "կամ" ;
lin both7and_DConj = mkConj "և՛" ;
lin either7or_DConj = mkConj "կամ" ;
lin if_then_Conj = mkConj "ապա" ;
lin but_PConj = mkPConj "բայց" ;
lin therefore_PConj = mkPConj "հետևաբար" ;
lin otherwise_PConj = mkPConj "այլապես" ;
lin in_Prep = postPrep [] Loc ;
lin on_Prep = postPrep "վրա" Dat ;
lin to_Prep = postPrep [] Dat ;
lin from_Prep = postPrep [] Ablat ;
lin with_Prep = postPrep [] Instr ;
lin without_Prep = postPrep "առանց" Dat ;
lin for_Prep = postPrep "համար" Dat ;
lin during_Prep = postPrep "ընթացքում" Dat ;
lin after_Prep = postPrep "հետո" Ablat ;
lin before_Prep = postPrep "առաջ" Ablat ;
lin under_Prep = postPrep "տակ" Dat ;
lin above_Prep = postPrep "վերևում" Dat ;
lin behind_Prep = postPrep "հետևում" Dat ;
lin between_Prep = postPrep "միջև" Dat ;
lin through_Prep = postPrep "միջով" Dat ;
lin by8agent_Prep = postPrep "կողմից" Dat ;
lin by8means_Prep = postPrep [] Instr ;
lin possess_Prep = postPrep [] Dat ;
lin part_Prep = postPrep [] Ablat ;
lin except_Prep = postPrep "բացի" Ablat ;
lin this_Quant = mkQuant "այս" ;
lin that_Quant = mkQuant "այդ" ;
lin no_Quant = mkQuant "ոչ մի" ;
lin every_Det = mkDet "ամեն" Sg ;
lin few_Det = mkDet "քիչ" Pl ;
lin many_Det = mkDet "շատ" Pl ;
lin much_Det = mkDet "շատ" Sg ;
lin someSg_Det = mkDet "որոշ" Sg ;
lin somePl_Det = mkDet "որոշ" Pl ;
lin all_Predet = mkPredet "բոլոր" ;
lin only_Predet = mkPredet "միայն" ;
lin most_Predet = mkPredet "մեծ մասը" ;
lin not_Predet = mkPredet "ոչ" ;
lin very_AdA = mkAdA "շատ" ;
lin too_AdA = mkAdA "չափազանց" ;
lin almost_AdA = mkAdA "գրեթե" ;
lin almost_AdN = mkAdN "գրեթե" ;
lin at_least_AdN = mkAdN "առնվազն" ;
lin at_most_AdN = mkAdN "առավելագույնը" ;
lin here_Adv = mkAdv "այստեղ" ;
lin there_Adv = mkAdv "այնտեղ" ;
lin everywhere_Adv = mkAdv "ամենուր" ;
lin somewhere_Adv = mkAdv "ինչ-որ տեղ" ;
lin always_AdV = mkAdV "միշտ" ;
lin quite_Adv = mkAdv "բավականին" ;
lin when_Subj = mkSubj "երբ" ;
lin if_Subj = mkSubj "եթե" ;
lin because_Subj = mkSubj "որովհետև" ;
lin although_Subj = mkSubj "թեև" ;
lin that_Subj = mkSubj "որ" ;
lin whatSg_IP = mkIP "ինչ" ;
lin whatPl_IP = mkIP "ինչեր" ;
lin whoSg_IP = mkIP "ով" ;
lin whoPl_IP = mkIP "ովքեր" ;
lin which_IQuant = mkIQuant "որ" ;
lin how_IAdv = mkIAdv "ինչպես" ;
lin when_IAdv = mkIAdv "երբ" ;
lin where_IAdv = mkIAdv "որտեղ" ;
lin why_IAdv = mkIAdv "ինչու" ;
lin how8many_IDet = mkIDet "քանի" ;
lin how8much_IAdv = mkIAdv "որքան" ;
lin as_CAdv = mkCAdv "այնքան" ;
lin more_CAdv = mkCAdv "ավելի" ;
lin less_CAdv = mkCAdv "պակաս" ;
lin can_VV, can8know_VV = mkVV (mkV "կարողանալ") ;
lin must_VV = mkVV (mkV "պարտավորվել") ;
lin want_VV = mkVV (mkV "ցանկանալ") ;
lin have_V2 = mkV2 (mkV "ունենալ") ;
lin everybody_NP = simpleNP "բոլորը" Pl P3 ;
lin everything_NP = simpleNP "ամեն ինչ" Sg P3 ;
lin somebody_NP = simpleNP "ինչ-որ մեկը" Sg P3 ;
lin something_NP = simpleNP "ինչ-որ բան" Sg P3 ;
lin nobody_NP = simpleNP "ոչ ոք" Sg P3 ;
lin nothing_NP = simpleNP "ոչինչ" Sg P3 ;
lin please_Voc = mkVoc "խնդրում եմ" ;
lin yes_Utt = {s="այո"} ;
lin no_Utt = {s="ոչ"} ;
}
