concrete CatSqi of Cat = CommonX ** open ParamX,Prelude,ResSqi in {
  lincat A = Adj ;
  lincat A2 = Adj ** {c2 : Compl} ;
  lincat V, VA, VV, VS, VQ = Verb ;
  lincat V2, V2S, V2Q = Verb ** {c2 : Compl} ;
  lincat V3, V2A, V2V = Verb ** {c2,c3 : Compl} ;
  lincat Prep = Compl ;
  lincat ACard = {s : Str} ;
  lincat AP = {s : Species => Case => Gender => Number => Str} ;
  lincat CN = Noun ;
  lincat Card = {s : Str} ;
  lincat Cl = {s : Str} ;
  lincat ClSlash = {s : Str} ;
  lincat Comp = {s : Str} ;
  lincat Conj = {s : Str} ;
  lincat DAP = {s : Str} ;
  lincat Decimal = {s : Str; n : Number; hasDot : Bool} ;
  lincat Det = {s : Case => Gender => Str; spec : Species; n : Number} ;
  lincat Digits = {s : Str; n : Number; tail : DTail} ;
  lincat GN = {s : Str} ;
  lincat IComp = {s : Str} ;
  lincat IDet = {s : Str} ;
  lincat IP = {s : Str} ;
  lincat IQuant = {s : Str} ;
  lincat Imp = {s : Str} ;
  lincat LN = {s : Str} ;
  lincat N = Noun ;
  lincat N2 = {s : Species => Case => Number => Str; g : Gender;
               c2 : {s : Str}} ;
  lincat N3 = {s : Species => Case => Number => Str; g : Gender;
               c2 : {s : Str}; c3 : {s : Str}} ;
  lincat NP = {s : Case => Str; a : Agr} ;
  lincat Num = {s : Str; n : Number} ;
  lincat Numeral = {s : Str} ;
  lincat Ord = {s : Str} ;
  lincat PN = {s : Str} ;
  lincat Predet = {s : Str} ;
  lincat Pron = {s: Case => Str; acc_clit, dat_clit : Str; a : Agr} ;
  lincat QCl = {s : Str} ;
  lincat QS = {s : Str} ;
  lincat Quant = {s : Case => Gender => Number => Str; spec : Species} ;
  lincat RCl = {s : Str} ;
  lincat RP = {s : Str} ;
  lincat RS = {s : Str} ;
  lincat S = {s : Str} ;
  lincat SN = {s : Str} ;
  lincat SSlash = {s : Str} ;
  lincat Subj = {s : Str} ;
  lincat VP = {indicative : Tense => Number => Person => Case => Str;
               participle : Case => Str;
               pres_optative : Number => Person => Case => Str;
               perf_optative : Number => Person => Case => Str;
               pres_admirative : Number => Person => Case => Str;
               imperf_admirative : Number => Person => Case => Str} ;
  lincat VPSlash = {indicative : Tense => Number => Person => Str;
                    imperative : Number => Str; participle : Str;
                    pres_optative : Number => Person => Str;
                    perf_optative : Number => Person => Str;
                    pres_admirative : Number => Person => Str;
                    imperf_admirative : Number => Person => Str} ;
}
