concrete GrammarTEMPLATE of Grammar =
  NounTEMPLATE,
  VerbTEMPLATE,
  AdjectiveTEMPLATE,
  AdverbTEMPLATE,
  NumeralTEMPLATE,
  SentenceTEMPLATE,
  QuestionTEMPLATE,
  RelativeTEMPLATE,
  ConjunctionTEMPLATE,
  PhraseTEMPLATE,
  TextX,
  StructuralTEMPLATE,
  IdiomTEMPLATE,
  TenseX ;