concrete CatKaz of Cat = CommonX ** open Prelude,ResKaz in {
  lincat A = {s : Str} ;
  lincat A2 = A ** {c2 : Compl} ;
  lincat ACard = {s : Str} ;
  lincat AP = {s : Str} ;
  lincat CN = {s : Case => Str} ;
  lincat Card = {s : Str} ;
  lincat Cl = {infinitive : Case => Str} ;
  lincat ClSlash = {s : Str} ;
  lincat Comp = {s : Str} ;
  lincat Conj = {s : Str} ;
  lincat DAP = {s : Str} ;
  lincat Decimal = {s : Str} ;
  lincat Det = {s : Str; n : Number} ;
  lincat Digits = {s : Str} ;
  lincat GN = {s : Str} ;
  lincat IComp = {s : Str} ;
  lincat IDet = {s : Str} ;
  lincat IP = {s : Str} ;
  lincat IQuant = {s : Str} ;
  lincat Imp = {s : Str} ;
  lincat LN = {s : Str} ;
  lincat N = {s : Case => Number => Str;
              poss : Number => Person => Number => Str} ;
  lincat N2 = {s : Case => Number => Str;
               poss : Number => Person => Number => Str; c2 : {s : Str}} ;
  lincat N3 = {s : Case => Number => Str;
               poss : Number => Person => Number => Str; c2 : {s : Str};
               c3 : {s : Str}} ;
  lincat NP = {s : Case => Str} ;
  lincat Num = {s : Str; n : Number} ;
  lincat Numeral = {s : Str} ;
  lincat Ord = {s : Str} ;
  lincat PN = {s : Str} ;
  lincat Predet = {s : Str} ;
  lincat Prep = Compl ;
  lincat Pron = {s : Str} ;
  lincat QCl = {s : Str} ;
  lincat QS = {s : Str} ;
  lincat Quant = {s : Str} ;
  lincat RCl = {s : Str} ;
  lincat RP = {s : Str} ;
  lincat RS = {s : Str} ;
  lincat S = {s : Str} ;
  lincat SN = {s : Str} ;
  lincat SSlash = {s : Str} ;
  lincat Subj = {s : Str} ;
  lincat V = Verb ;
  lincat VV,VS,VQ,VA = Verb ;
  lincat V2 = Verb ** {c2 : Compl} ;
  lincat V3,V2A,V2S,V2Q,V2V = Verb ** {c2,c3 : Compl} ;
  lincat VP = {infinitive : Case => Str;
               indicative : {fut : Case => Str;
                             pres : {progressive : Polarity => Case => Str;
                                     noAspect : Polarity => Case => Str};
                             past : {perfect : Polarity => Case => Str;
                                     progressive : Polarity => Case => Str;
                                     noAspect : Polarity => Case => Str}};
               subjunctive : Person => Case => Str} ;
  lincat VPSlash = {infinitive : Str;
                    indicative : {fut : Str;
                            pres : {progressive : Polarity => Person => Number => Str;
                                    noAspect : Polarity => Person => Number => Str};
                            past : {perfect : Polarity => Person => Number => Str;
                                    progressive : Polarity => Person => Number => Str;
                                    noAspect : Polarity => Person => Number => Str}};
                    imperative : Polarity => Formality => Number => Str;
                    subjunctive : Person => Number => Str} ;
}
