concrete ExtraLexiconLat of ExtraLexiconLatAbs = CatLat ** open ParadigmsLat in {
  lin
    friend_Fem_N = mkN "amica" ; -- -i/-ae m./f. (Langenscheidts)
    baby_Fem_N = mkN "infans" "infantis" feminine ;  -- Ranta; -antis m./f. (Langenscheidts)
    blue_Var_A = mkA "caeruleus" ; -- 3 (Langenscheidts)
    boss_Fem_N = mkN "dux" "ducis" feminine ; -- ducis m./f. (Langenscheidts)
    bread_Neutr_N = mkN "pane" "panis" neuter ; -- -is m./n. (Langenscheidts)
    cat_Var_N = mkN "felis" "felis" feminine ; -- -is f. (Langenscheidts)
    cousin_Fem_N = mkN "consobrina" ; -- -i/-ae m./f. (Langenscheidts)
    cow_Fem_N = mkN "bos" "bovis" feminine ; -- bovis (gen. pl. boum, dat./abl. pl. bobus/bubus) m./f. (Langenscheidts)
    dog_Fem_N = mkN "canis" "canis" feminine ; -- -is m./f. (Langenscheidts)
    enemy_Fem_N = mkN "hostis" "hostis" feminine ; -- -is m./f. (Langenscheidts)
    policeman_Fem_N = mkN "custos" "custodis" feminine ; -- -odis m./f. (Langenscheidts)
    priest_Fem_N = mkN "sacerdos" "sacerdotis" feminine ; -- -dotis m./f. (Langenscheidts)
    snake_Fem_N = mkN "serpens" "serpentis" feminine ; -- -entis m./f. (Langenscheidts)
    student_Fem_N = mkN "discipula" ; -- -i/-ae m./f. (Langenscheidts)
    switch8on_Var_V2 = mkV2 (mkV "exstinguere" ) ; -- -ingo, -inxi, -inctum 3 (Langenscheidts)
    bark_Fem_N = mkN "cortex" "corticis" feminine ; -- -icis m./(f.) (Langenscheidts)
    blood_Var_N = mkN "sangis" "sanginis" masculine ; -- -inis m. (Langenscheidts)
    day_Fem_N = mkN "dies" "diei" feminine ; -- -ei m./f. (Langenscheidts)
    horn_Var_N = mkN "cornu" "cornus" neuter ; -- -us n. (Langenscheidts)
    liver_Var_N = mkN "iocur" "iocineris" neuter ; -- iecoris/iocineris n. (Langenscheidts)
    louse_Fem_N = mkN "pedis" "pedis" feminine ; -- -is m./f. (Langenscheidts)
    nose_Neutr_N = mkN "nasum" ; -- -i m./n. (Langenscheidts)
    rope_Fem_N = mkN "funis" "funis" feminine ; -- -is m.(/f.) (Langenscheidts)
    salt_Neutr_N = mkN "sal" "salis" neuter ; -- salis m./n. (Langenscheidts)
    stick_Neutr_N = mkN "baculum" ; -- -i n./m.
};